name: admin_cafe_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_date_pickers: ^0.4.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^1.1.6
  get: 4.6.5
  get_storage: ^2.0.3
  http_parser: ^4.0.2
  image_picker: ^0.8.6
  timeago: ^3.3.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/
